// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsCompTool
{
    internal sealed partial class Vsix
    {
        public const string Id = "Visual Studio Comparison.b7516115-191d-4065-afcb-8197ea8ba175";
        public const string Name = "Visual Studio Comparison Tools";
        public const string Description = @"Visual Studio Comparison Tools is an extension for Visual Studio which uses external tools to compare files, folders and clipboard. Features: Comparing two files, selecting folders for comparison from the solution explorer and comparing (and merging) clipboard to a file or selected area in a file. By default uses VSDiff to compare files. If Beyond Compare or WinDiff is found, then uses those. Updated for VS2022";
        public const string Language = "en-US";
        public const string Version = "3.1.4";
        public const string Author = "Mikko Halttunen";
        public const string Tags = "";
    }
}
