// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsCompTool
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VsCompToolString = "7ecfef92-365c-45d9-9b8f-1d74d43925ce";
        public static Guid VsCompTool = new Guid(VsCompToolString);

        public const string guidVsCompToolPackageCmdSetString = "aa9e628d-a118-4a7b-ad58-8a2a89354ab8";
        public static Guid guidVsCompToolPackageCmdSet = new Guid(guidVsCompToolPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int Compare = 0x0100;
        public const int MyMenuGroup2 = 0x1020;
    }
}